# Generated by Django 3.0.2 on 2020-01-24 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0003_auto_20200124_1855'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type_Expense',
            new_name='Expense_Type',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='type_expense',
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_type', to='expenses.Expense_Type'),
        ),
    ]
