# Generated by Django 3.0.2 on 2020-02-17 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date',
        ),
    ]
